In [2]:
import torch

In [5]:
device ="cuda" if torch.cuda.is_available() else "cpu"

In [8]:
mytensor= torch.tensor([[1,2,3],[1,2,3]], dtype = torch.float16, device = device)
mytensor
mytensor.device
mytensor.shape
mytensor.requires_grad

False

In [11]:
x = torch.empty(size=(3,3))
x

tensor([[-7.1124e+22,  3.0780e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.4460e-44],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])

In [13]:
x = torch.ones(size=(3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
x = torch.eye(3,3) #identity matrix
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
x = torch.linspace(start=0.1,end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [20]:
 x = torch.empty(size=(3,3)).normal_(mean=0, std=1)
x

tensor([[ 1.7769, -0.4246,  0.4620],
        [ 0.8537, -0.7804,  1.1550],
        [-0.6103, -1.7699, -0.5505]])

In [21]:
x = torch.empty(size=(3,3)).uniform_(0,1)
x

tensor([[0.2175, 0.7659, 0.3430],
        [0.9043, 0.7364, 0.3449],
        [0.6403, 0.1120, 0.1014]])

In [22]:
x = torch.diag(torch.ones(5))
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Intializing and Converting types

In [26]:
x = torch.arange(4)
x.bool()

tensor([False,  True,  True,  True])

In [28]:
print(x.short())
print(x.long())
print(x.half())


tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)


In [29]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [31]:
# add
z = torch.empty(3)
torch.add(x, y, out=z) # z= torch.add(x, y)
z

tensor([5., 7., 9.])

In [32]:
z = torch.empty(3)
torch.sub(x, y, out=z)
z

tensor([-3., -3., -3.])

In [33]:
z = torch.true_divide(x,y)
z

tensor([0.2500, 0.4000, 0.5000])

In [35]:
#multiplication
x = torch.rand(2,3)
y = torch.rand(3,5)
z= x.mm(y)
z = torch.mm(x,y)
z

tensor([[0.6740, 0.2898, 0.4886, 0.5877, 0.6304],
        [1.0845, 0.6537, 1.2877, 1.2998, 1.1582]])

In [37]:
x = torch.rand(2,3)
y = torch.rand(2,3)
torch.eq(x,y)

tensor([[False, False, False],
        [False, False, False]])

In [39]:
torch.sort(y, descending=False)

torch.return_types.sort(values=tensor([[0.6321, 0.6580, 0.6949],
        [0.4812, 0.5222, 0.7280]]), indices=tensor([[0, 1, 2],
        [0, 2, 1]]))

In [42]:
x = torch.tensor([1,0,1,1])
z = torch.any(x)
z

tensor(True)